<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controls\free-icon-human-4466332.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contacts.Model\Contacts.Model.csproj" />
    <ProjectReference Include="..\Contacts.ViewModel\Contacts.ViewModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Controls\free-icon-human-4466332.png" />
  </ItemGroup>

</Project>